# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.
# Project
version=26.x-1.0.0
group=xyz.hajsori
java_version=25
# Common
min_minecraft_version=26.1
excluded_minecraft_version=27.1
mod_name=Unhidden Advancements
mod_author=Hajsori
mod_id=unhidden_advancements
license=MIT
credits=
description=Shows all the hidden advancements!
neo_form_version=26.1-1
# Fabric
fabric_loader_version=0.18.5
# Forge
forge_version=62.0.4
forge_loader_version_range=[51,)
# NeoForge
neoforge_version=26.1.0.7-beta
neoforge_loader_version_range=[4,)
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
